import { ICommand } from '@adg/server-shared';

export const CREATE_PORTFOLIO_COMMAND = 'CreateUserCommand';
export interface CreatePortfolioPayload {
  PortfolioId?: string; // Can be pre-generated by client or generated by handler
  name: string;
  email: string;
}
export type CreatePortfolioCommand = ICommand<CreatePortfolioPayload>;

export const UPDATE_PORTFOLIO_NAME_COMMAND = 'UpdatePortfolioNameCommand';
export interface UpdatePortfolioNamePayload {
  name: string;
}
export type UpdatePortfolioNameCommand = ICommand<UpdatePortfolioNamePayload>;
