import { ICommand } from '@adg/server-shared';

export const CREATE_LOT_COMMAND = 'CreateLotCommand';
export interface CreateLotPayload {
  lotId?: string; // Can be pre-generated by client or generated by handler
  name: string;
  email: string;
}
export type CreateLotCommand = ICommand<CreateLotPayload>;

export const UPDATE_LOT_NAME_COMMAND = 'UpdateLotNameCommand';
export interface UpdateLotNamePayload {
  name: string;
}
export type UpdateLotNameCommand = ICommand<UpdateLotNamePayload>;
