import { ICommand } from '@adg/server-shared';

export const CREATE_USER_COMMAND = 'CreateUserCommand';
export interface CreateUserPayload {
  userId?: string; // Can be pre-generated by client or generated by handler
  name: string;
  email: string;
}
export type CreateUserCommand = ICommand<CreateUserPayload>;

export const UPDATE_USER_NAME_COMMAND = 'UpdateUserNameCommand';
export interface UpdateUserNamePayload {
  name: string;
}
export type UpdateUserNameCommand = ICommand<UpdateUserNamePayload>;
